server:
  port: 8080


spring:
  application:
    name: customer

  profiles:
    active: loc

  datasource:
    platform: postgres

  jpa:
    properties:
      org:
        hibernate:
          envers:
            default_schema: audit
    database: postgresql
