server:
  port: 8080


spring:
  application:
    name: customer

  profiles:
    active: loc

  datasource:
    platform: postgres
    url: jdbc:tc:postgresql:11-alpine:///customer-integrationtest
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    properties:
      org:
        hibernate:
          envers:
            default_schema: audit
    database: postgresql
